language: node_js
notifications:
  email: false
language: node_js
node_js:
  - "10"
  - "12"
  - "13"
# blocklist
branches:
  except:
    - develop
    - /^feature*/
    - /^bug*/
    - /^hotfix*/
    - /^support*/

# safelist
branches:
  only:
    - master
    - release
